#!/bin/bash

# Post-install script for the Discord Updater package, setting up the autostart feature

# Define the path to your update script
SCRIPT_PATH="/usr/local/bin/discord-updater.sh"

# Set the autostart file name and path
AUTOSTART_FILE_NAME="discord-updater-autostart.desktop"
AUTOSTART_FILE_PATH="${HOME}/.config/autostart/${AUTOSTART_FILE_NAME}"

# Create the autostart directory if it doesn't exist
mkdir -p "${HOME}/.config/autostart"

# Create the autostart file
echo "Creating autostart file..."
{
  echo "[Desktop Entry]"
  echo "Type=Application"
  echo "Name=Discord Updater"
  echo "Comment=Update Discord to the latest version"
  echo "Exec=${SCRIPT_PATH}"
  echo "Terminal=false"
  echo "Hidden=false"
  echo "X-GNOME-Autostart-enabled=true"
} > "${AUTOSTART_FILE_PATH}"

# Make the .desktop file executable
chmod +x "${AUTOSTART_FILE_PATH}"

echo "Autostart file created at ${AUTOSTART_FILE_PATH}"
